import JSZip from 'jszip'
import { BaseExporter } from './base-exporter'
import { ExportFormat, type ExportOptions } from './types'
import type { Component } from '@/editor/stores/components'
import { buildJsActionSnippets } from '../action-runtime'

export class ReactExporter extends BaseExporter {
  format = ExportFormat.REACT

  protected async generate(
    components: Component[],
    options: ExportOptions
  ): Promise<Blob> {
    const {
      projectName,
      packageManager = 'npm',
      includeTypeScript = true,
      includeESLint = true,
      includePrettier = true
    } = options

    const zip = new JSZip()
    const ext = includeTypeScript ? 'tsx' : 'jsx'

    zip.file('package.json', this.generatePackageJson(projectName))
    zip.file('README.md', this.generateReadme(projectName, packageManager))
    zip.file('.gitignore', this.generateGitignore())

    if (includeTypeScript) {
      zip.file('tsconfig.json', this.generateTsConfig())
      zip.file('tsconfig.node.json', this.generateTsConfigNode())
    }

    if (includeESLint) {
      zip.file('.eslintrc.json', this.generateEslintConfig(includeTypeScript))
    }

    if (includePrettier) {
      zip.file('.prettierrc', this.generatePrettierConfig())
    }

    zip.file('vite.config.ts', this.generateViteConfig())
    zip.file('index.html', this.generateIndexHtml(projectName))

    const srcFolder = zip.folder('src')!
    srcFolder.file(`main.${ext}`, this.generateMain(includeTypeScript))
    srcFolder.file(`App.${ext}`, this.generateApp(components))
    srcFolder.file('index.css', this.generateGlobalStyles())

    const componentsFolder = srcFolder.folder('components')!
    this.generateComponents(components, componentsFolder, ext)

    const publicFolder = zip.folder('public')!
    publicFolder.file('vite.svg', '')

    return await zip.generateAsync({ type: 'blob' })
  }

  private generatePackageJson(projectName: string): string {
    return JSON.stringify({
      name: projectName,
      private: true,
      version: '1.0.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview',
        lint: 'eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0'
      },
      dependencies: {
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        antd: '^5.12.0'
      },
      devDependencies: {
        '@types/react': '^18.2.43',
        '@types/react-dom': '^18.2.17',
        '@typescript-eslint/eslint-plugin': '^6.14.0',
        '@typescript-eslint/parser': '^6.14.0',
        '@vitejs/plugin-react': '^4.2.1',
        eslint: '^8.55.0',
        'eslint-plugin-react-hooks': '^4.6.0',
        'eslint-plugin-react-refresh': '^0.4.5',
        typescript: '^5.2.2',
        vite: '^5.0.8'
      }
    }, null, 2)
  }

  private generateReadme(projectName: string, packageManager: string): string {
    const installCmd = packageManager === 'npm' ? 'npm install' : 
                      packageManager === 'pnpm' ? 'pnpm install' : 'yarn'
    const devCmd = packageManager === 'npm' ? 'npm run dev' :
                  packageManager === 'pnpm' ? 'pnpm dev' : 'yarn dev'

    return `# ${projectName}

This project was generated by Low-Code Platform.

## Getting Started

Install dependencies:

\`\`\`bash
${installCmd}
\`\`\`

Run development server:

\`\`\`bash
${devCmd}
\`\`\`

Build for production:

\`\`\`bash
${packageManager === 'npm' ? 'npm run build' : packageManager === 'pnpm' ? 'pnpm build' : 'yarn build'}
\`\`\`
`
  }

  private generateGitignore(): string {
    return `node_modules
dist
dist-ssr
*.local

.DS_Store
.env
.env.local
.env.*.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

.idea
.vscode
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
`
  }

  private generateTsConfig(): string {
    return JSON.stringify({
      compilerOptions: {
        target: 'ES2020',
        useDefineForClassFields: true,
        lib: ['ES2020', 'DOM', 'DOM.Iterable'],
        module: 'ESNext',
        skipLibCheck: true,
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: 'react-jsx',
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true
      },
      include: ['src'],
      references: [{ path: './tsconfig.node.json' }]
    }, null, 2)
  }

  private generateTsConfigNode(): string {
    return JSON.stringify({
      compilerOptions: {
        composite: true,
        skipLibCheck: true,
        module: 'ESNext',
        moduleResolution: 'bundler',
        allowSyntheticDefaultImports: true
      },
      include: ['vite.config.ts']
    }, null, 2)
  }

  private generateEslintConfig(includeTypeScript: boolean): string {
    return JSON.stringify({
      env: {
        browser: true,
        es2020: true
      },
      extends: [
        'eslint:recommended',
        ...(includeTypeScript ? [
          'plugin:@typescript-eslint/recommended',
          'plugin:react-hooks/recommended'
        ] : ['plugin:react/recommended'])
      ],
      ignorePatterns: ['dist', '.eslintrc.cjs'],
      parser: includeTypeScript ? '@typescript-eslint/parser' : undefined,
      plugins: includeTypeScript ? ['react-refresh'] : undefined,
      rules: {
        'react-refresh/only-export-components': [
          'warn',
          { allowConstantExport: true }
        ]
      }
    }, null, 2)
  }

  private generatePrettierConfig(): string {
    return JSON.stringify({
      semi: false,
      singleQuote: true,
      tabWidth: 2,
      trailingComma: 'none',
      printWidth: 100
    }, null, 2)
  }

  private generateViteConfig(): string {
    return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`
  }

  private generateIndexHtml(projectName: string): string {
    return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
  }

  private generateMain(includeTypeScript: boolean): string {
    return `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App${includeTypeScript ? '.tsx' : '.jsx'}'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')${includeTypeScript ? '!' : ''}).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
`
  }

  private generateApp(components: Component[]): string {
    const componentSet = new Set<string>()

    this.collectUniqueComponents(components, componentSet)

    const imports: string[] = []
    componentSet.forEach(name => {
      if (name !== 'Container' && name !== 'Page') {
        imports.push(`import ${name} from './components/${name}'`)
      }
    })

    const importsStr = imports.length > 0
      ? imports.join('\n') + '\n\n'
      : ''

    const jsx = this.renderComponentsToJSX(components, 2)
    const hasMultipleRoots = jsx.split('\n').filter(line => line.trim() && line.trim().startsWith('<')).length > 1

    return `${importsStr}function App() {
  return (
${hasMultipleRoots ? '    <>\n' : ''}${jsx}
${hasMultipleRoots ? '    </>\n' : ''}  )
}

export default App
`
  }

  private renderComponentsToJSX(components: Component[], indent: number): string {
    const indentStr = ' '.repeat(indent)
    
    return components.map(comp => {
      if (comp.name === 'Page') {
        return comp.children 
          ? this.renderComponentsToJSX(comp.children, indent)
          : ''
      }

      const { name, props, styles, children, events } = comp
      const tag = name === 'Container' ? 'div' : name

      const attrs: string[] = []
      
      if (styles && Object.keys(styles).length > 0) {
        const styleStr = JSON.stringify(styles)
        attrs.push(`style=${styleStr}`)
      }

      if (props) {
        Object.entries(props).forEach(([key, value]) => {
          if (key === 'text') return
          if (typeof value === 'string') {
            attrs.push(`${key}="${this.escapeJSX(value)}"`)
          } else if (typeof value === 'boolean') {
            if (value) attrs.push(key)
          } else {
            attrs.push(`${key}={${JSON.stringify(value)}}`)
          }
        })
      }

      if (events && events.onClick) {
        const { actionType, actionConfig } = events.onClick
        const snippets = buildJsActionSnippets(actionType, actionConfig, (text) => this.escapeJSX(text))
        if (snippets.length > 0) {
          attrs.push(`onClick={() => { ${snippets.join('; ')} }}`)
        }
      }

      const attrsStr = attrs.length > 0 ? ' ' + attrs.join(' ') : ''

      if (children && children.length > 0) {
        return `${indentStr}<${tag}${attrsStr}>
${this.renderComponentsToJSX(children, indent + 2)}
${indentStr}</${tag}>`
      } else {
        const text = typeof props?.text === 'string' ? props.text : null
        if (text) {
          return `${indentStr}<${tag}${attrsStr}>${this.escapeJSX(text)}</${tag}>`
        }
      }
      if (this.isSelfClosing(name)) {
        return `${indentStr}<${tag}${attrsStr} />`
      } else {
        return `${indentStr}<${tag}${attrsStr}></${tag}>`
      }
    }).join('\n')
  }

  private escapeJSX(text: string): string {
    return text
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "\\'")
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
  }

  private isSelfClosing(componentName: string): boolean {
    return componentName === 'Input' || componentName === 'Image'
  }

  private generateGlobalStyles(): string {
    return `* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`
  }

  private generateComponents(
    components: Component[],
    folder: JSZip,
    ext: string
  ): void {
    const componentSet = new Set<string>()
    this.collectUniqueComponents(components, componentSet)

    componentSet.forEach(name => {
      if (name !== 'Page' && name !== 'Container') {
        folder.file(`${name}.${ext}`, this.generateComponentFile(name, ext))
      }
    })
  }

  private collectUniqueComponents(components: Component[], set: Set<string>): void {
    components.forEach(comp => {
      set.add(comp.name)
      if (comp.children) {
        this.collectUniqueComponents(comp.children, set)
      }
    })
  }

  private generateComponentFile(componentName: string, ext: string): string {
    const propsType = ext === 'tsx' ? ': React.HTMLAttributes<HTMLElement>' : ''

    switch (componentName) {
      case 'Button':
        return `import { CSSProperties } from 'react'

interface ButtonProps {
  type?: 'primary' | 'default'
  children?: React.ReactNode
  style?: CSSProperties
  onClick?: () => void
}

export default function Button({ type = 'default', children, style, onClick }: ButtonProps) {
  const baseStyle: CSSProperties = {
    padding: '4px 15px',
    fontSize: '14px',
    borderRadius: '6px',
    border: '1px solid transparent',
    cursor: 'pointer',
    transition: 'all 0.2s',
    backgroundColor: type === 'primary' ? '#1677ff' : 'white',
    color: type === 'primary' ? 'white' : 'rgba(0, 0, 0, 0.88)',
    borderColor: type === 'primary' ? '#1677ff' : '#d9d9d9'
  }

  return (
    <button style={{ ...baseStyle, ...style }} onClick={onClick}>
      {children}
    </button>
  )
}
`
      case 'Input':
        return `import { CSSProperties } from 'react'

interface InputProps {
  placeholder?: string
  value?: string
  style?: CSSProperties
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void
}

export default function Input({ placeholder, value, style, onChange }: InputProps) {
  const baseStyle: CSSProperties = {
    padding: '4px 11px',
    fontSize: '14px',
    lineHeight: '1.5715',
    border: '1px solid #d9d9d9',
    borderRadius: '6px',
    transition: 'all 0.2s'
  }

  return (
    <input
      type="text"
      placeholder={placeholder}
      value={value}
      style={{ ...baseStyle, ...style }}
      onChange={onChange}
    />
  )
}
`
      case 'Text':
        return `import { CSSProperties } from 'react'

interface TextProps {
  children?: React.ReactNode
  style?: CSSProperties
}

export default function Text({ children, style }: TextProps) {
  return <span style={style}>{children}</span>
}
`
      case 'Title':
        return `import { CSSProperties } from 'react'

interface TitleProps {
  level?: 1 | 2 | 3 | 4 | 5 | 6
  children?: React.ReactNode
  style?: CSSProperties
}

export default function Title({ level = 1, children, style }: TitleProps) {
  const Tag = \`h\${level}\` as keyof JSX.IntrinsicElements
  return <Tag style={style}>{children}</Tag>
}
`
      case 'Image':
        return `import { CSSProperties } from 'react'

interface ImageProps {
  src?: string
  alt?: string
  width?: number | string
  height?: number | string
  style?: CSSProperties
}

export default function Image({ src, alt, width, height, style }: ImageProps) {
  return <img src={src} alt={alt} width={width} height={height} style={style} />
}
`
      case 'Card':
        return `import { CSSProperties } from 'react'

interface CardProps {
  title?: string
  children?: React.ReactNode
  style?: CSSProperties
}

export default function Card({ title, children, style }: CardProps) {
  const baseStyle: CSSProperties = {
    background: 'white',
    borderRadius: '8px',
    border: '1px solid #f0f0f0',
    padding: '16px',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.03)'
  }

  return (
    <div style={{ ...baseStyle, ...style }}>
      {title && <h3 style={{ marginBottom: '12px' }}>{title}</h3>}
      {children}
    </div>
  )
}
`
      default:
        return `export default function ${componentName}(props${propsType}) {
  return <div {...props} />
}
`
    }
  }
}
