import JSZip from 'jszip'
import { BaseExporter } from './base-exporter'
import { ExportFormat, type ExportOptions } from './types'
import type { Component } from '@/editor/stores/components'
import { buildJsActionSnippets } from '../action-runtime'

export class VueExporter extends BaseExporter {
  format = ExportFormat.VUE

  protected async generate(
    components: Component[],
    options: ExportOptions
  ): Promise<Blob> {
    const {
      projectName,
      packageManager = 'npm',
      includeTypeScript = true,
      includeESLint = true,
      includePrettier = true
    } = options

    const zip = new JSZip()

    zip.file('package.json', this.generatePackageJson(projectName))
    zip.file('README.md', this.generateReadme(projectName, packageManager))
    zip.file('.gitignore', this.generateGitignore())

    if (includeTypeScript) {
      zip.file('tsconfig.json', this.generateTsConfig())
      zip.file('tsconfig.node.json', this.generateTsConfigNode())
    }

    if (includeESLint) {
      zip.file('.eslintrc.cjs', this.generateEslintConfig(includeTypeScript))
    }

    if (includePrettier) {
      zip.file('.prettierrc', this.generatePrettierConfig())
    }

    zip.file('vite.config.ts', this.generateViteConfig())
    zip.file('index.html', this.generateIndexHtml(projectName))
    zip.file('env.d.ts', this.generateEnvDts())

    const srcFolder = zip.folder('src')!
    srcFolder.file('main.ts', this.generateMain())
    srcFolder.file('App.vue', this.generateApp(components))
    srcFolder.file('style.css', this.generateGlobalStyles())

    const componentsFolder = srcFolder.folder('components')!
    this.generateComponents(components, componentsFolder, options.themeColors)

    const publicFolder = zip.folder('public')!
    publicFolder.file('vite.svg', '')

    return await zip.generateAsync({ type: 'blob' })
  }

  private generatePackageJson(projectName: string): string {
    return JSON.stringify({
      name: projectName,
      private: true,
      version: '1.0.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vue-tsc && vite build',
        preview: 'vite preview'
      },
      dependencies: {
        vue: '^3.3.11',
        'ant-design-vue': '^4.1.0'
      },
      devDependencies: {
        '@vitejs/plugin-vue': '^4.5.2',
        typescript: '^5.2.2',
        vite: '^5.0.8',
        'vue-tsc': '^1.8.25'
      }
    }, null, 2)
  }

  private generateReadme(projectName: string, packageManager: string): string {
    const installCmd = packageManager === 'npm' ? 'npm install' : 
                      packageManager === 'pnpm' ? 'pnpm install' : 'yarn'
    const devCmd = packageManager === 'npm' ? 'npm run dev' :
                  packageManager === 'pnpm' ? 'pnpm dev' : 'yarn dev'

    return `# ${projectName}

This project was generated by Low-Code Platform.

## Getting Started

Install dependencies:

\`\`\`bash
${installCmd}
\`\`\`

Run development server:

\`\`\`bash
${devCmd}
\`\`\`

Build for production:

\`\`\`bash
${packageManager === 'npm' ? 'npm run build' : packageManager === 'pnpm' ? 'pnpm build' : 'yarn build'}
\`\`\`
`
  }

  private generateGitignore(): string {
    return `node_modules
dist
dist-ssr
*.local

.DS_Store
.env
.env.local
.env.*.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

.idea
.vscode
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
`
  }

  private generateTsConfig(): string {
    return JSON.stringify({
      compilerOptions: {
        target: 'ES2020',
        useDefineForClassFields: true,
        module: 'ESNext',
        lib: ['ES2020', 'DOM', 'DOM.Iterable'],
        skipLibCheck: true,
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: 'preserve',
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true
      },
      include: ['src/**/*.ts', 'src/**/*.d.ts', 'src/**/*.tsx', 'src/**/*.vue'],
      references: [{ path: './tsconfig.node.json' }]
    }, null, 2)
  }

  private generateTsConfigNode(): string {
    return JSON.stringify({
      compilerOptions: {
        composite: true,
        skipLibCheck: true,
        module: 'ESNext',
        moduleResolution: 'bundler',
        allowSyntheticDefaultImports: true
      },
      include: ['vite.config.ts']
    }, null, 2)
  }

  private generateEslintConfig(includeTypeScript: boolean): string {
    return `module.exports = {
  env: {
    browser: true,
    es2021: true
  },
  extends: [
    'eslint:recommended',
    'plugin:vue/vue3-recommended',
    ${includeTypeScript ? "'plugin:@typescript-eslint/recommended'" : ''}
  ],
  parserOptions: {
    ecmaVersion: 'latest',
    ${includeTypeScript ? "parser: '@typescript-eslint/parser'," : ''}
    sourceType: 'module'
  },
  plugins: ['vue'${includeTypeScript ? ", '@typescript-eslint'" : ''}],
  rules: {}
}
`
  }

  private generatePrettierConfig(): string {
    return JSON.stringify({
      semi: false,
      singleQuote: true,
      tabWidth: 2,
      trailingComma: 'none',
      printWidth: 100
    }, null, 2)
  }

  private generateViteConfig(): string {
    return `import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
})
`
  }

  private generateIndexHtml(projectName: string): string {
    return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`
  }

  private generateEnvDts(): string {
    return `/// <reference types="vite/client" />
`
  }

  private generateMain(): string {
    return `import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import Antd from 'ant-design-vue'
import 'ant-design-vue/dist/reset.css'

createApp(App).use(Antd).mount('#app')
`
  }

  private generateApp(components: Component[]): string {
    const imports: string[] = []
    const componentMap = new Map<string, number>()

    this.collectComponentImports(components, imports, componentMap)

    const importsStr = imports.length > 0 
      ? imports.join('\n') + '\n' 
      : ''

    const template = this.renderComponentsToTemplate(components, 1)
    const hasMultipleRoots = template.split('\n').filter(line => line.trim() && line.trim().startsWith('<')).length > 1

    return `<template>
${hasMultipleRoots ? '  <div>\n' : ''}${template}
${hasMultipleRoots ? '  </div>\n' : ''}</template>

<script setup lang="ts">
${importsStr}</script>

<style scoped>
</style>
`
  }

  private collectComponentImports(
    components: Component[],
    imports: string[],
    componentMap: Map<string, number>
  ): void {
    components.forEach((comp) => {
      if (comp.name !== 'Page') {
        const count = componentMap.get(comp.name) || 0
        componentMap.set(comp.name, count + 1)
      }
      if (comp.children) {
        this.collectComponentImports(comp.children, imports, componentMap)
      }
    })

    componentMap.forEach((_, name) => {
      if (name !== 'Container') {
        imports.push(`import ${name} from './components/${name}.vue'`)
      }
    })
  }

  private renderComponentsToTemplate(components: Component[], indent: number): string {
    const indentStr = '  '.repeat(indent)
    
    return components.map(comp => {
      if (comp.name === 'Page') {
        return comp.children 
          ? this.renderComponentsToTemplate(comp.children, indent)
          : ''
      }

      const { name, props, styles, children, events } = comp
      const tag = name === 'Container' ? 'div' : name

      const attrs: string[] = []
      
      if (styles && Object.keys(styles).length > 0) {
        const styleStr = this.styleObjectToString(styles as Record<string, unknown>)
        attrs.push(`:style="{ ${styleStr} }"`)
      }

      if (props) {
        Object.entries(props).forEach(([key, value]) => {
          if (key === 'text') return
          if (typeof value === 'string') {
            attrs.push(`${key}="${this.escapeHTML(value)}"`)
          } else {
            attrs.push(`:${key}="${JSON.stringify(value)}"`)
          }
        })
      }

      if (events && events.onClick) {
        const { actionType, actionConfig } = events.onClick
        const snippets = buildJsActionSnippets(actionType, actionConfig, (text) => this.escapeHTML(text))
        if (snippets.length > 0) {
          attrs.push(`@click="() => { ${snippets.join('; ')} }"`)
        }
      }

      const attrsStr = attrs.length > 0 ? ' ' + attrs.join(' ') : ''

      if (children && children.length > 0) {
        return `${indentStr}<${tag}${attrsStr}>
${this.renderComponentsToTemplate(children, indent + 1)}
${indentStr}</${tag}>`
      } else {
        const text = typeof props?.text === 'string' ? props.text : null
        if (text) {
          return `${indentStr}<${tag}${attrsStr}>${text}</${tag}>`
        }
      }
      if (this.isSelfClosing(name)) {
        return `${indentStr}<${tag}${attrsStr} />`
      } else {
        return `${indentStr}<${tag}${attrsStr}></${tag}>`
      }
    }).join('\n')
  }

  private escapeHTML(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;')
  }

  private styleObjectToString(styles: Record<string, unknown>): string {
    return Object.entries(styles)
      .map(([key, value]) => {
        const vueKey = key
        const vueValue = typeof value === 'string' ? `'${value}'` : value
        return `${vueKey}: ${vueValue}`
      })
      .join(', ')
  }

  private isSelfClosing(componentName: string): boolean {
    return componentName === 'Input' || componentName === 'Image'
  }

  private generateGlobalStyles(): string {
    return `* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`
  }

  private generateComponents(
    components: Component[],
    folder: JSZip,
    themeColors?: { primary: string; primaryHover: string }
  ): void {
    const componentSet = new Set<string>()
    this.collectUniqueComponents(components, componentSet)

    componentSet.forEach(name => {
      if (name !== 'Page' && name !== 'Container') {
        folder.file(`${name}.vue`, this.generateComponentFile(name, themeColors))
      }
    })
  }

  private collectUniqueComponents(components: Component[], set: Set<string>): void {
    components.forEach(comp => {
      set.add(comp.name)
      if (comp.children) {
        this.collectUniqueComponents(comp.children, set)
      }
    })
  }

  private generateComponentFile(componentName: string, themeColors?: { primary: string; primaryHover: string }): string {
    const primary = themeColors?.primary || '#1677ff'
    switch (componentName) {
      case 'Button':
        return `<template>
  <button :style="buttonStyle" @click="handleClick">
    <slot />
  </button>
</template>

<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'

interface Props {
  type?: 'primary' | 'default'
}

const props = withDefaults(defineProps<Props>(), {
  type: 'default'
})

const emit = defineEmits<{
  click: []
}>()

const buttonStyle = computed((): CSSProperties => ({
  padding: '4px 15px',
  fontSize: '14px',
  borderRadius: '6px',
  border: '1px solid transparent',
  cursor: 'pointer',
  transition: 'all 0.2s',
  backgroundColor: props.type === 'primary' ? '${primary}' : 'white',
  color: props.type === 'primary' ? 'white' : 'rgba(0, 0, 0, 0.88)',
  borderColor: props.type === 'primary' ? '${primary}' : '#d9d9d9'
}))

const handleClick = () => {
  emit('click')
}
</script>
`
      case 'Input':
        return `<template>
  <input
    type="text"
    :placeholder="placeholder"
    :value="modelValue"
    :style="inputStyle"
    @input="handleInput"
  />
</template>

<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'

interface Props {
  placeholder?: string
  modelValue?: string
}

defineProps<Props>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const inputStyle = computed((): CSSProperties => ({
  padding: '4px 11px',
  fontSize: '14px',
  lineHeight: '1.5715',
  border: '1px solid #d9d9d9',
  borderRadius: '6px',
  transition: 'all 0.2s'
}))

const handleInput = (e: Event) => {
  const target = e.target as HTMLInputElement
  emit('update:modelValue', target.value)
}
</script>
`
      case 'Text':
        return `<template>
  <span>
    <slot />
  </span>
</template>

<script setup lang="ts">
</script>
`
      case 'Title':
        return `<template>
  <component :is="tag">
    <slot />
  </component>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  level?: 1 | 2 | 3 | 4 | 5 | 6
}

const props = withDefaults(defineProps<Props>(), {
  level: 1
})

const tag = computed(() => \`h\${props.level}\`)
</script>
`
      case 'Image':
        return `<template>
  <img :src="src" :alt="alt" :width="width" :height="height" />
</template>

<script setup lang="ts">
interface Props {
  src?: string
  alt?: string
  width?: number | string
  height?: number | string
}

defineProps<Props>()
</script>
`
      case 'Card':
        return `<template>
  <div :style="cardStyle">
    <h3 v-if="title" style="margin-bottom: 12px">{{ title }}</h3>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'

interface Props {
  title?: string
}

defineProps<Props>()

const cardStyle = computed((): CSSProperties => ({
  background: 'white',
  borderRadius: '8px',
  border: '1px solid #f0f0f0',
  padding: '16px',
  boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.03)'
}))
</script>
`
      default:
        return `<template>
  <div>
    <slot />
  </div>
</template>

<script setup lang="ts">
</script>
`
    }
  }
}
